# Generated by Django 4.2.3 on 2024-08-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingWritingBooksApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
