# Generated by Django 4.2.3 on 2024-08-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingWritingBooksApp', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
