# Generated by Django 4.2.3 on 2024-08-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingWritingBooksApp', '0006_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, upload_to='book_files/'),
        ),
    ]
