# Generated by Django 4.2.3 on 2024-08-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingWritingBooksApp', '0009_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=True, max_length=255),
        ),
    ]
