# Generated by Django 4.2.3 on 2024-08-06 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingWritingBooksApp', '0010_comment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
