# Generated by Django 4.2.3 on 2024-08-08 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingWritingBooksApp', '0012_comment_post_post_updated_at_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ReadingWritingBooksApp.post'),
        ),
    ]
