# Generated by Django 4.2.3 on 2024-08-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingWritingBooksApp', '0013_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
    ]
