# Generated by Django 4.2.3 on 2024-08-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingWritingBooksApp', '0014_remove_comment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_books', to='ReadingWritingBooksApp.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='library',
            field=models.ManyToManyField(blank=True, related_name='liked_by_user', to='ReadingWritingBooksApp.book'),
        ),
    ]
